power <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?", stringsAsFactors=FALSE)
power2 <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
power2$datetime <- strptime(with(power2, paste(Date, Time)), format = "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(power2$datetime, power2$Sub_metering_1, type = "l", xlab="", ylab = "Energy sub metering")
lines(power2$datetime, power2$Sub_metering_2, col = "red")
lines(power2$datetime, power2$Sub_metering_3, col = "blue")
legend("topright", legend = names(power2)[7:9], col = c("black", "red", "blue"), lty=1 )
dev.off()

